#ifndef THREAD_SAFE_COLLECTIONS_THREAD_SAFE_COLLECTIONS_H_
#define THREAD_SAFE_COLLECTIONS_THREAD_SAFE_COLLECTIONS_H_


#include "queue.h"

#endif /* THREAD_SAFE_COLLECTIONS_THREAD_SAFE_COLLECTIONS_H_ */
